### ISSUE TITLE
v2.1好像有点问题，和v2.0结果完全不一样

### ISSUE THREAD

**Issue by chilllyn** [SQRPI/JiaGuoMeng#34]

**Comment by LLawlight** [comment]
是的 同样的配置 加了自动升级之后 秒伤差距太大了
![image](https://user-images.githubusercontent.com/17525377/66114614-cbcbd600-e601-11e9-8e77-08dbb2aa7ee9.png)

**Comment by SQRPI** [comment]
我传错版本了。。马上去改一下。。
